#!/usr/bin/env python3
"""Regenerates assets/css/shapes.css from the SVG sources.

    python3 tools/build-shape-css.py

Run it after adding, removing or re-exporting a logo or shape. The aspect
ratios are read straight off each file's viewBox, so they cannot drift from
the artwork.
"""

import glob
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

HEADER = '''/* ==========================================================================
   Behkooshan shape and logo library
   Generated by tools/build-shape-css.py from the SVG sources.

   Both sets ship with a currentColor fill and are drawn through a mask, so a
   mark takes the colour of whatever context it sits in. Per the design guide
   a shape is punctuation, not pattern: one per view, green or bone, never a
   gradient and never a stroke.

   Usage:  <span class="bk-shape bk-shape--05" aria-hidden="true"></span>
   Size it with inline-size; the aspect ratio comes from the class.

   The url() has to live in this stylesheet rather than in a style attribute.
   A url() inside a custom property resolves against the stylesheet that uses
   it, not the document, so declaring it here keeps every deploy path correct.
   ========================================================================== */

.bk-shape,
.bk-logo {
  display: block;
  aspect-ratio: var(--shape-ratio, 1);
  background-color: currentColor;
  -webkit-mask: var(--shape) no-repeat center / contain;
  mask: var(--shape) no-repeat center / contain;
}
'''

LOGOS = [
    ("logo-mark", "mark"),
    ("logo-lockup", "lockup"),
    ("logo-lockup-fa", "lockup-fa"),
    ("logotype", "wordmark"),
]


def viewbox_ratio(path):
    match = re.search(r'viewBox="0 0 ([\d.]+) ([\d.]+)"', Path(path).read_text(encoding="utf-8"))
    if not match:
        raise SystemExit(f"{path} has no parseable viewBox")
    return match.group(1), match.group(2)


def rule(selector, url, width, height):
    return f'{selector} {{\n  --shape: url("{url}");\n  --shape-ratio: {width} / {height};\n}}\n'


def main():
    parts = [HEADER, "\n/* --- Logos ---------------------------------------------------------------- */\n"]

    for name, suffix in LOGOS:
        width, height = viewbox_ratio(ROOT / f"assets/logos/{name}.svg")
        parts.append(rule(f".bk-logo--{suffix}", f"../logos/{name}.svg", width, height))

    parts.append("\n/* --- Shapes --------------------------------------------------------------- */\n")

    for path in sorted(glob.glob(str(ROOT / "assets/shapes/abstract-*.svg"))):
        number = re.search(r"abstract-(\d+)", path).group(1)
        width, height = viewbox_ratio(path)
        parts.append(rule(f".bk-shape--{number}", f"../shapes/abstract-{number}.svg", width, height))

    out = ROOT / "assets/css/shapes.css"
    out.write_text("\n".join(parts), encoding="utf-8")
    print(f"{len(parts) - 3} classes written to {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
